name: Build Docker on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mostrar vers√£o
        run: echo "Nova tag detectada: ${{ github.ref_name }}"

      - name: Build imagem
        run: |
          docker build \
            --build-arg APP_VERSION=${{ github.ref_name }} \
            --build-arg APP_COMMIT=${{ github.sha }} \
            --build-arg APP_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            -t laravel-ci-lab:${{ github.ref_name }} .

